Add log page, remove adblock function

diff --git a/root/usr/bin/ssr-switch b/root/usr/bin/ssr-switch
--- a/root/usr/bin/ssr-switch
+++ b/root/usr/bin/ssr-switch
@@ -21,8 +21,8 @@ CONFIG_SWTICH_FILE=/var/etc/${NAME}_t.json
 [ -n "$2" ] && switch_time=$2
 
 uci_get_by_name() {
-  local ret=$(uci get $NAME.$1.$2 2>/dev/null)
-  echo ${ret:=$3}
+	local ret=$(uci get $NAME.$1.$2 2>/dev/null)
+	echo ${ret:=$3}
 }
 
 uci_get_by_type() {
@@ -34,125 +34,125 @@ DEFAULT_SERVER=$(uci_get_by_type global global_server)
 CURRENT_SERVER=$DEFAULT_SERVER
 
 check_proxy() {
-  /usr/bin/ssr-check www.google.com  80 $switch_time 1
-  if [ "$?" == "0" ]; then
-    return 0
-  else
-    /usr/bin/ssr-check www.baidu.com  80 $switch_time 1
-    if [ "$?" == "0" ]; then
-      return 1
-    else
-      return 2
-    fi
-  fi
-  return 0
+	/usr/bin/ssr-check www.google.com  80 $switch_time 1
+  	if [ "$?" == "0" ]; then
+    	return 0
+  	else
+    	/usr/bin/ssr-check www.baidu.com  80 $switch_time 1
+    	if [ "$?" == "0" ]; then
+      		return 1
+    	else
+      		return 2
+    	fi
+  	fi
+  	return 0
 }
 
 
 test_proxy() {
-  local servername=$(uci_get_by_name $1 server)
-  local serverport=$(uci_get_by_name $1 server_port)
-  ret=$(ping -c 3 $servername  | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }') 
-  [ -z "$ret"  ] && return 1
-  [ "$ret" -gt "50" ] && return 1
-  ipset add ss_spec_wan_ac $servername 2>/dev/null
-  ret=$?
-  /usr/bin/ssr-check $servername $serverport $switch_time 
-  local ret2=$?
-  if [ "$ret" = "0" ] ;then
-    ipset del ss_spec_wan_ac $servername 2>/dev/null
-  fi
-  if [ "$ret2" = "0" ] ;then
-    return 0
-  else
-    return 1
-  fi
+	local servername=$(uci_get_by_name $1 server)
+  	local serverport=$(uci_get_by_name $1 server_port)
+  
+  	ret=$(ping -c 3 $servername  | grep 'loss' | awk -F ',' '{ print $3 }' | awk -F "%" '{ print $1 }') 
+  	[ -z "$ret"  ] && return 1
+  	[ "$ret" -gt "50" ] && return 1
+  	ipset add ss_spec_wan_ac $servername 2>/dev/null
+  	ret=$?
+  	/usr/bin/ssr-check $servername $serverport $switch_time 
+  	local ret2=$?
+  	if [ "$ret" = "0" ] ;then
+    	ipset del ss_spec_wan_ac $servername 2>/dev/null
+  	fi
+  	if [ "$ret2" = "0" ] ;then
+    	return 0
+  	else
+    	return 1
+  	fi
 }
 
 search_proxy() {
-  let server_count=server_count+1
-  [ "$normal_flag" = "1" -a "$server_count" -le "$server_locate" ] && return 0
-  [ "$(uci_get_by_name $1 switch_enable)" != "1"  ]  && return 1
-  [ $ENABLE_SERVER != nil ] && return 0
-  [ "$1" = "$CURRENT_SERVER" ] && return 0
-  local servername=$(uci_get_by_name $1 server)
-  local serverport=$(uci_get_by_name $1 server_port)
-  ipset add ss_spec_wan_ac $servername 2>/dev/null
-  ret=$?
-  /usr/bin/ssr-check $servername  $serverport $switch_time 
-  local ret2=$?
-  if [ "$ret" = "0" ] ;then
-    ipset del ss_spec_wan_ac $servername 2>/dev/null
-  fi
-  if [ "$ret2" = "0" ] ;then
-    server_locate=$server_count
-    ENABLE_SERVER=$1
-    return 0
-  else
-    return 1
-  fi
-
+	let server_count=server_count+1
+  	[ "$normal_flag" = "1" -a "$server_count" -le "$server_locate" ] && return 0
+  	[ "$(uci_get_by_name $1 switch_enable)" != "1"  ]  && return 1
+  	[ $ENABLE_SERVER != nil ] && return 0
+  	[ "$1" = "$CURRENT_SERVER" ] && return 0
+  	local servername=$(uci_get_by_name $1 server)
+  	local serverport=$(uci_get_by_name $1 server_port)
+  	ipset add ss_spec_wan_ac $servername 2>/dev/null
+  	ret=$?
+  	/usr/bin/ssr-check $servername  $serverport $switch_time 
+  	local ret2=$?
+  	if [ "$ret" = "0" ] ;then
+    	ipset del ss_spec_wan_ac $servername 2>/dev/null
+  	fi
+  	if [ "$ret2" = "0" ] ;then
+    	server_locate=$server_count
+    	ENABLE_SERVER=$1
+    	return 0
+  	else
+    	return 1
+  	fi
 }
 
 select_proxy() {
 
-  config_load $NAME
-  ENABLE_SERVER=nil
-  mkdir -p /var/run /var/etc
-  server_count=0
-  config_foreach search_proxy servers
+	config_load $NAME
+ 	ENABLE_SERVER=nil
+ 	mkdir -p /var/run /var/etc
+ 	server_count=0
+ 	config_foreach search_proxy servers
 
 }
 
 
 switch_proxy() {
-  /etc/init.d/shadowsocksr restart $1
-  return 0
+	/etc/init.d/shadowsocksr restart $1
+ 	return 0
 }
 
 start() {
 
-  [ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1"  ]  && return 1
+	[ $(uci_get_by_name $DEFAULT_SERVER kcp_enable) = "1"  ]  && return 1
 
-  while [ "1" = "1" ]  
-  do 
-    sleep $cycle_time
+	while [ "1" = "1" ]  
+  	do 
+    	sleep $cycle_time
       
-    if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ] ;then
-    #echo "not default proxy"
+    	if [ "$CURRENT_SERVER" != "$DEFAULT_SERVER" ] ;then
+    		
+    		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server is not default Main server, try to switch back." >> /tmp/openwrt-ssr.log
 
-      if test_proxy $DEFAULT_SERVER  ;then
-      #echo "switch to default proxy"
-        CURRENT_SERVER=$DEFAULT_SERVER
-        switch_proxy $CURRENT_SERVER 
-        logger -t "$NAME" "switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!"
-        continue
-      fi
-    fi
+      		if test_proxy $DEFAULT_SERVER  ;then
+      			echo "$(date "+%Y-%m-%d %H:%M:%S") Main server is avilable." >> /tmp/openwrt-ssr.log
+        		CURRENT_SERVER=$DEFAULT_SERVER
+        		switch_proxy $CURRENT_SERVER 
+        		echo "switch to default ["$(uci_get_by_name $CURRENT_SERVER server)"] proxy!"  >> /tmp/openwrt-ssr.log
+        		continue
+      		fi
+    	fi
 
     
-    check_proxy  
-    current_ret=$?
+    	check_proxy  
+    	current_ret=$?
     
-    if [ "$current_ret" = "1" ] ;then
+    	if [ "$current_ret" = "1" ] ;then
       
-      #echo "current error"
+      		echo "$(date "+%Y-%m-%d %H:%M:%S") Current server error, try to switch another server." >> /tmp/openwrt-ssr.log
+      		select_proxy
       
-      select_proxy
-      if [ "$ENABLE_SERVER" != nil ] ;then
-        #echo $(uci_get_by_name $new_proxy server)
-        CURRENT_SERVER=$ENABLE_SERVER
-        switch_proxy $CURRENT_SERVER
-        normal_flag=1
-        logger -t "$NAME" "switch proxy ["$(uci_get_by_name $CURRENT_SERVER server)"] success!"
-        #echo "switch ok"
-      else
-        normal_flag=0 
-      fi
-    else
-        normal_flag=0   
-    fi
+      		if [ "$ENABLE_SERVER" != nil ] ;then
+        		echo "$(date "+%Y-%m-%d %H:%M:%S") Another server is avilable, now switching server." >> /tmp/openwrt-ssr.log
+        		CURRENT_SERVER=$ENABLE_SERVER
+        		switch_proxy $CURRENT_SERVER
+        		normal_flag=1
+        		echo "$(date "+%Y-%m-%d %H:%M:%S") ShadowsocksR server switch OK" >> /tmp/openwrt-ssr.log
+      		else
+        		normal_flag=0 
+      		fi
+    	else
+        	normal_flag=0   
+    	fi
 
 
-  done
+  	done
 }
